# thetagpu, openmpi, nvhpc (for cpu math libraries)
# module load nvhpc-nompi

#
# Definition of MACROS

PATH_TO_NVCC = $(shell which nvcc)
PATH_TO_NVHPC = $(shell echo ${PATH_TO_NVCC} | rev | cut -d '/' -f 4- | rev)

$(info PATH_TO_NVHPC= [${PATH_TO_NVHPC}])

CXX = mpicxx
CXXFLAGS = -g -fopenmp -O3 -std=c++0x
#CXXFLAGS += -I$(CUDA)/include

CUDA_CXX = nvcc
CUDA_CXXFLAGS = 

CPP = cpp -P -traditional
CPPFLAGS =

LD = $(CXX)
LIB = -L$(PATH_TO_NVHPC)/cuda/lib64 -lcuda -lcudart
LIB += -L$(PATH_TO_NVHPC)/math_libs/lib64 -lcusolver -lcublas -lcusparse
LIB += -L$(PATH_TO_NVHPC)/compilers/lib -lblas

BINROOT=./
EX=a.out
SHELL=/bin/sh

# -- subset of src files with cuda kernels
CUDA_SRC = pm_cuda.cpp offload.cpp
CUDA_OBJ = $(CUDA_SRC:.cpp=.o)

SRC = $(filter-out $(CUDA_SRC), $(wildcard *.cpp))
INC = $(wildcard *.h)
OBJ = $(SRC:.cpp=.o)

#
# -- target : 	Dependencies
# --		Rule to create target

$(EX): 	$(OBJ) $(CUDA_OBJ)
	$(LD) -o $@ $(CXXFLAGS) $(OBJ) $(CUDA_OBJ) $(LIB)

####################################################################

$(OBJ): %.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $<

$(CUDA_OBJ): %.o: %.cpp
	$(CUDA_CXX) -x cu $(CUDA_CXXFLAGS) -c $< -o $@

#
# -- Remove *.o and *~ from the directory
clean:
	rm -f *.o *~
#
# -- Remove *.o, *~, and executable from the directory
realclean:
	rm -f *.o *~ ./$(EX)

#
# -- Simple dependencies

$(OBJ) : $(INC)
$(CUDA_OBJ) : $(INC)
